[package]
name = "timetrace2"
version = "0.1.0"
authors = ["Paul Richards <paul.richards@gmail.com>"]

[dependencies]
memmap = "0.7.0"
rand = "0.5.3"
stopwatch = "0.0.7"
log = "0.4.3"
env_logger = "0.5.11"
owning_ref = "0.4.0"
