[package]
name = "timetrace2"
version = "0.1.0"
authors = ["Paul Richards <paul.richards@gmail.com>"]
edition = "2018"

[dependencies]
memmap = "0.7"
rand = "0.7"
stopwatch = "0.0.7"
log = "0.4"
env_logger = "0.7"
owning_ref = "0.4"

[dev-dependencies]
tempfile = "3.0"
